CREATE DATABASE "notesdb"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Russian_Russia.1251'
    LC_CTYPE = 'Russian_Russia.1251'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

CREATE TABLE IF NOT EXISTS public.notes
(
    id_note integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_user integer NOT NULL,
    heading character varying(100) COLLATE pg_catalog."default" NOT NULL,
    date_creation date NOT NULL,
    date_change date NOT NULL,
    text text COLLATE pg_catalog."default",
    CONSTRAINT notes_pkey PRIMARY KEY (id_note)
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.notes
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.notes_aud
(
    id_note integer NOT NULL,
    rev integer NOT NULL,
    revtype integer,
    date_change date,
    date_creation date,
    heading character varying(100) COLLATE pg_catalog."default",
    id_user integer,
    text text COLLATE pg_catalog."default",
    CONSTRAINT notes_aud_pkey PRIMARY KEY (id_note, rev),
    CONSTRAINT fklcbm0d0nddfou7tcksil5s1ih FOREIGN KEY (rev)
        REFERENCES public.revinfo (rev) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.notes_aud
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.revinfo
(
    rev integer NOT NULL,
    revtstmp bigint,
    CONSTRAINT revinfo_pkey PRIMARY KEY (rev)
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.revinfo
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.users
(
    id_user integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    role character varying(10) COLLATE pg_catalog."default" NOT NULL,
    username character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id_user)
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
    OWNER to postgres;